### PR TITLE
build: allow symfony 4 install

### PR DESCRIPTION
**Pull request by gsdevme**

### CODE REVIEW

**Comment by shieldo** [comment]
@gsdevme Have updated this branch with a Travis build matrix update - also I have PHPStan added to the project in a PR https://github.com/usemarkup/OEmbedBundle/pull/13 which should help guard against oversights 👍

**Comment by shieldo** [comment]
@gsdevme Could we move forward here?

**Comment by shieldo** [comment]
btw have made https://github.com/usemarkup/OEmbedBundle/pull/14 as a PR into this one, and rebased this on top of latest master so PHPStan can run.

**Comment by gsdevme** [comment]
Closing in favour of the work by Douglas

**Comment by gsdevme** [comment]
Going to just re-make this PR

**Comment by shieldo** [comment]
@gsdevme Would the PR come from a recreated `allow-sf4` branch? That work has been deleted for now and risks getting lost.

**Pull request closed without merging**
